[project]
name = "chrono_vs_lubridate_t"
description = "Comparing T's chrono package with R's lubridate"
authors = []

[dependencies]

[r-dependencies]
packages = ["arrow", "lubridate", "jsonlite"]

[py-dependencies]
version = "python314"
packages = []

[jl-dependencies]
version = "lts"
packages = []

[additional-tools]
packages = []

[latex]
packages = []

[t]
min_version = "0.55.0"

[nixpkgs]
date = ""

