[project]
name = "basic_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "arrow",]

[py-dependencies]
version = "python314"
packages = []

[additional-tools]
packages = [ "quarto",]

[t]
min_version = "0.51.2"
