[project]
name = "model_comparison_with_glance_t"
version = "0.1.0"
description = "A demo comparing R and Python models using the newly expanded glance()."

[dependencies]

[r-dependencies]
packages = [ "dplyr", "readr", "arrow", "jsonlite", "pmml", "XML", "r2pmml",]

[py-dependencies]
version = "python313"
packages = [ "scikit-learn", "pandas", "pyarrow", "sklearn2pmml", "numpy", "scipy", "statsmodels",]

[additional-tools]
packages = [ "quarto", "jre", "jpmml-evaluator",]

[t]
min_version = "0.55.0"
