#!/usr/bin/env bash
# script to rebuild the demos site in tlang/docs/demos/
set -e

# Target directories
TLANG_ROOT="${TLANG_ROOT:-/home/brodrigues/Documents/repos/tlang}"
DEMOS_ROOT="${DEMOS_ROOT:-/home/brodrigues/Documents/repos/t_demos}"
DOCS_DEMO_DIR="$TLANG_ROOT/docs/demos"

echo "=== T Demos Site Rebuilder ==="
mkdir -p "$DOCS_DEMO_DIR"

# Template for demos.md (User Guide page)
DEMOS_MD="$TLANG_ROOT/docs/demos.md"
cat <<EOF > "$DEMOS_MD"
# T Pipeline Demos

This page showcases live reports generated by **T** during pipeline execution.
Each link below points to a Quarto report rendered as part of a T pipeline node.

## List of Demos

EOF

cd "$DEMOS_ROOT"

# Loop over each directory in t_demos
for demo_dir in */; do
    # Skip directories that don't look like T projects
    if [ ! -f "${demo_dir}tproject.toml" ]; then
        continue
    fi
    
    demo_name=$(basename "$demo_dir")
    
    # Look for any .t file in src/
    entry_point=$(ls "${demo_dir}"src/*.t 2>/dev/null | head -n 1)
    
    if [ -n "$entry_point" ]; then
        echo "--> Building demo: $demo_name ($entry_point)"
        
        # Absolute paths for T
        ABS_ENTRY=$(realpath "$entry_point")
        ABS_DEMO_ROOT=$(realpath "$demo_dir")
        
        cd "$ABS_DEMO_ROOT"
        
        # 1. Clean previous build artifacts
        rm -rf pipeline-output/ _pipeline/
        
        # 2. Check if it has a report.qmd, if not, skip report generation for now
        if [ ! -f "src/report.qmd" ]; then
            echo "    (No report.qmd found, skipping HTML generation for this demo)"
            cd "$DEMOS_ROOT"
            continue
        fi

        # Provision the tlang Quarto extension manually (simulating what T does in nix develop)
        mkdir -p src/_extensions
        rm -rf src/_extensions/tlang
        cp -r "$TLANG_ROOT/editors/quarto/tlang/_extensions/tlang" src/_extensions/
        
        # 3. Compile the pipeline using dune exec for the T compiler
        echo "    Executing T pipeline..."
        # We run from the demo root so relative paths in tproject.toml work.
        # But we use the T compiler from TLANG_ROOT via nix develop.
        nix develop "$TLANG_ROOT" --command dune exec --root "$TLANG_ROOT" src/repl.exe -- run --unsafe "$ABS_ENTRY"
        
        # 4. Copy the report to the docs directory
        if [ -d "pipeline-output/report/artifact" ]; then
            rm -rf "$DOCS_DEMO_DIR/$demo_name"
            mkdir -p "$DOCS_DEMO_DIR/$demo_name"
            # pipeline_copy() copies $out/ to pipeline-output/report/
            # so the actual content is in pipeline-output/report/artifact/
            cp -r pipeline-output/report/artifact/* "$DOCS_DEMO_DIR/$demo_name/"
            
            # Extract title from YAML frontmatter in report.qmd
            report_title=$(grep "title:" "src/report.qmd" | head -n 1 | sed 's/title:[[:space:]]*//' | sed 's/^"//;s/"$//')
            if [ -z "$report_title" ]; then report_title="$demo_name"; fi
            
            # Find the main HTML file
            base_qmd=$(basename "src/report.qmd" .qmd)
            main_html="$DOCS_DEMO_DIR/$demo_name/${base_qmd}.html"
            if [ ! -f "$main_html" ]; then
                main_html=$(find "$DOCS_DEMO_DIR/$demo_name" -name "*.html" | head -n 1)
            fi
            
            if [ -n "$main_html" ] && [ -f "$main_html" ]; then
                html_rel_path="demos/$demo_name/$(basename "$main_html")"
                echo "- [$report_title]($html_rel_path)" >> "$DEMOS_MD"
                echo "    ✓ Report published: $report_title"
            else
                echo "    ! HTML file not found after build"
            fi
        else
            echo "    ! Pipeline built successfully but 'report' node artifact missing"
        fi
        
        cd "$DEMOS_ROOT"
    fi
done

# Finally, rebuild the main tlang documentation site to include common styles and index update
echo "=== Rebuilding T Documentation Site ==="
cd "$TLANG_ROOT/docs"
./build.sh

echo ""
echo "Success! The T Pipeline Demos page is now live at: $TLANG_ROOT/docs/demos.html"
