[r-dependencies]
packages = [ "arrow", "jsonlite",]

[py-dependencies]
packages = [ "pandas", "pyarrow",]

[project]
name = "multi_deserializer_t"
description = "A T data analysis project"

[t]
min_version = "0.51.2"
