[project]
name = "r_git_pkgs_t"
description = "Installs brotools from GitHub and uses sample_mode() in an R node"

[r-dependencies]
brotools = { git = "https://github.com/b-rodrigues/brotools", rev = "7e6f0b1a3f03bf50dc6a9583ef67590f488af8bc" }
packages = ["jsonlite"]

[py-dependencies]
version = "python314"
packages = ["deepdiff"]

[jl-dependencies]
version = "lts"
packages = ["JSON"]

[t]
min_version = "0.54.0"
