[project]
name = "r_py_xgboost_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "dplyr", "yardstick", "arrow",]

[additional-tools]
packages = [ "quarto",]

[py-dependencies]
version = "python313"
packages = [ "numpy", "pandas", "scikit-learn", "xgboost", "pyarrow",]

[t]
min_version = "0.51.2"
