[project]
name = "glm_basic_py_t"
description = "GLM Example: Basic Python logistic regression"

[t]
min_version = "0.51.2"

[py-dependencies]
packages = ["statsmodels", "pandas", "pyarrow", "scikit-learn", "sklearn2pmml", "numpy", "scipy"]

[additional-tools]
packages = ["jpmml-evaluator", "jpmml-statsmodels", "jre"]
