[project]
name = "isl_lab4_smarket_t"
description = "ISL Lab Migration: test_lab4_smarket.t"

[dependencies]

[r-dependencies]
packages = ["XML", "arrow", "jsonlite", "r2pmml"]

[py-dependencies]
version = "python314"
packages = ["numpy", "pandas", "pyarrow", "scikit-learn", "scipy", "sklearn2pmml", "statsmodels"]

[additional-tools]
packages = ["jpmml-evaluator", "jpmml-statsmodels", "jre"]

[latex]
packages = []

[t]
min_version = "0.51.2"

[nixpkgs]
date = ""
