[project]
name = "glm_titanic_t"
description = "GLM Example: Titanic survival logistic regression"

[t]
min_version = "0.51.2"

[r-dependencies]
packages = ["arrow", "XML", "jsonlite", "r2pmml"]

[py-dependencies]
packages = ["statsmodels", "pandas", "pyarrow", "numpy", "scikit-learn", "scipy", "sklearn2pmml"]

[additional-tools]
packages = ["jpmml-evaluator", "jpmml-statsmodels", "jre"]
