[project]
name = "many_inputs_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "readr",]

[py-dependencies]
packages = [ "polars",]

[additional-tools]
packages = [ "quarto",]

[t]
min_version = "0.51.2"
