[project]
name = "many_inputs_t"
description = "A T data analysis project"
authors = []

[dependencies]

[r-dependencies]
packages = ["readr", "arrow", "jsonlite", "knitr", "rmarkdown"]

[py-dependencies]
version = "python314"
packages = ["polars", "ipykernel", "nbclient", "nbformat", "pandas", "pyarrow", "pyyaml"]

[jl-dependencies]
version = "lts"
packages = []

[additional-tools]
packages = ["quarto", "which"]

[latex]
packages = []

[t]
min_version = "0.55.0"

[nixpkgs]
date = ""

