[project]
name = "many_unserialize_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "dplyr", "readr",]

[py-dependencies]
version = "python314"
packages = []

[additional-tools]
packages = [ "quarto",]

[t]
min_version = "0.51.2"
