[project]
name = "py_uv_workspace_t"
description = "Demonstrates UV workspace Python dependency resolver in T pipelines"

[py-dependencies]
resolver = "uv"
workspace = "python"

[t]
min_version = "0.54.0"
