[project]
name = "onnx_exchange_t"
description = "A demo showcasing the exchange of a Python Scikit-Learn ONNX model to T-Lang"

[dependencies]

[r-dependencies]
packages = ["XML", "arrow", "jsonlite", "onnx", "r2pmml"]

[py-dependencies]
version = "python314"
packages = ["scikit-learn", "skl2onnx", "onnxruntime", "pandas", "numpy", "pyarrow", "scipy", "sklearn2pmml", "statsmodels"]

[julia-dependencies]
version = "lts"
packages = ["Arrow", "DataFrames", "ONNX", "ONNXRunTime"]

[additional-tools]
packages = ["jpmml-evaluator", "jre"]

[latex]
packages = []

[t]
min_version = "0.52.0"

[nixpkgs]
date = ""
