[project]
name = "onnx_exchange_t"
description = "Train models in R and Python, exchange via ONNX, and predict in all runtimes."
nixpkgs_date = "2026-04-02"

[dependencies]

[r-dependencies]
packages = [ "onnx", "dplyr", "arrow", "pmml", "XML",]

[py-dependencies]
version = "python313"
packages = [ "onnx", "onnxruntime", "skl2onnx", "scikit-learn", "pandas", "numpy", "pyarrow", "sklearn2pmml",]

[t]
min_version = "0.51.2"
