[project]
name = "check_nodes_pipeline_t"
description = "A comprehensive demo to check nodes in multi-language pipelines (T, R, Python, Bash)"

[dependencies]

[r-dependencies]
packages = [ "dplyr", "arrow", "ggplot2", "r2pmml",]

[py-dependencies]
version = "python313"
packages = [ "pandas", "pyarrow", "numpy", "scikit-learn", "statsmodels", "sklearn2pmml",]

[additional-tools]
packages = [ "quarto",]

[t]
min_version = "0.51.2"
