[project]
name = "julia_interop_t"
description = "A demo of T and Julia interoperation in a pipeline"

[julia-dependencies]
version = "lts"
packages = ["DataFrames", "CSV", "StatsModels"]

[t]
min_version = "0.55.0"

[nixpkgs]
date = ""
