[project]
name = "julia_interop_t"
description = "A demo of T and Julia interoperation in a pipeline"

[julia-dependencies]
version = "lts"
packages = ["DataFrames", "CSV"]

[t]
min_version = "0.52.0"

[nixpkgs]
date = ""
