[project]
name = "yanai_lercher_2020_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "dplyr", "ggplot2",]

[py-dependencies]
version = "python313"
packages = [ "numpy", "pillow",]

[t]
min_version = "0.51.2"
