[project]
name = "r_py_json_t"
description = "A T data analysis project"

[dependencies]
# T packages this project depends on
# Format: package = { git = "repository-url", tag = "version" }
# Example:
# stats = { git = "https://github.com/t-lang/stats", tag = "v0.5.0" }

[r-dependencies]
# R packages this project depends on
# Example:
# packages = ["dplyr", "ggplot2"]
packages = ["dplyr", "jsonlite", "arrow"]

[py-dependencies]
# Python packages this project depends on
version = "python313"
# Example:
# packages = ["pandas", "numpy"]
packages = ["polars", "pandas", "pyarrow"]

[additional-tools]
packages = ["quarto"]

[t]
# Minimum T language version required
min_version = "0.5.0"
