[project]
name = "r_py_json_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "dplyr", "jsonlite", "arrow",]

[py-dependencies]
version = "python313"
packages = [ "polars", "pandas", "pyarrow",]

[additional-tools]
packages = [ "quarto",]

[t]
min_version = "0.51.2"
