[project]
name = "onnx_neural_world_age"
version = "0.1.0"
authors = ["Bruno Rodrigues <bruno@brodrigues.co>"]
description = "Testing World Age safety with Flux in T-lang"

[py-dependencies]
version = "python314"
packages = ["scikit-learn", "skl2onnx", "onnxruntime", "pandas", "numpy"]

[julia-dependencies]
version = "lts"
packages = ["Flux", "Zygote", "ChainRulesCore", "ZygoteRules", "JSON", "JLD2", "CSV", "DataFrames"]

[nixpkgs]
date = "2026-04-02"

[t]
min_version = "0.55.0"
