[project]
name = "plotting_pipeline_t"
description = "Demo of ggplot2 and matplotlib metadata capture"

[dependencies]

[r-dependencies]
packages = ["ggplot2", "jsonlite"]

[py-dependencies]
version = "python314"
packages = ["matplotlib", "pandas", "seaborn", "plotly", "kaleido", "altair", "vl-convert-python", "bokeh", "selenium", "plotnine", "cloudpickle"]

[additional-tools]
packages = []

[latex]
packages = []

[t]
min_version = "0.51.3"

[nixpkgs]
date = ""
