[project]
name = "glm_basic_r_t"
description = "GLM Example: Basic R logistic regression"

[t]
min_version = "0.51.2"

[r-dependencies]
packages = ["arrow"]

[additional-tools]
packages = ["jpmml-evaluator", "jre"]
