[project]
name = "onnx_neuralnet_t"
description = "A demo showcasing ONNX exchange for a Scikit-Learn MLPClassifier neural network"

[dependencies]

[r-dependencies]
packages = []

[py-dependencies]
version = "python314"
packages = ["scikit-learn", "skl2onnx", "onnxruntime", "pandas", "numpy"]

[julia-dependencies]
version = "lts"
packages = ["Flux", "JSON"]

[additional-tools]
packages = []

[latex]
packages = []

[t]
min_version = "0.55.0"

[nixpkgs]
date = ""
