[project]
name = "shn_t"
description = "A T data analysis project"

[dependencies]

[r-dependencies]
packages = [ "chronicler", "rix",]

[py-dependencies]
version = "python314"
packages = []

[t]
min_version = "0.51.2"

[additional-tools]
packages = [ "gawk",]
